import LegalLayout from '@/components/LegalLayout';

export const metadata = {
  title: 'Terms of Service · Inbox Pipeline',
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="17 April 2026">
      <p>
        By using Inbox Pipeline (the &quot;Service&quot;) you agree to these terms. If you don&apos;t
        agree, don&apos;t use the Service. These terms are short on purpose.
      </p>

      <h2>What Inbox Pipeline is</h2>
      <p>
        Inbox Pipeline is open-source software that reads your Gmail inbox, classifies incoming emails with
        AI, extracts lead details, and drafts replies for you to review and send. It&apos;s designed for
        solo service businesses.
      </p>
      <p>
        The source code is available under an open-source licence at{' '}
        <a href="https://github.com/stoddnetworks/inbox-pipeline" target="_blank" rel="noopener noreferrer">
          github.com/stoddnetworks/inbox-pipeline
        </a>. You can self-host it and modify it. A hosted demo version is available at inbox-pipeline.vercel.app.
      </p>

      <h2>Your account</h2>
      <p>
        You&apos;re responsible for your account, your Gmail credentials, and anything that happens under
        your account. Keep your password secure.
      </p>
      <p>
        You need to be at least 18 years old to use the Service.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Don&apos;t use Inbox Pipeline to:
      </p>
      <ul>
        <li>Send spam, unsolicited commercial messages, or anything illegal</li>
        <li>Access Gmail accounts you don&apos;t own or have permission to use</li>
        <li>Attempt to reverse engineer, break, or abuse the Service&apos;s infrastructure</li>
        <li>Violate Google&apos;s Gmail API Terms or Anthropic&apos;s acceptable use policy</li>
      </ul>

      <h2>Third-party services</h2>
      <p>
        Inbox Pipeline relies on Google (Gmail), Anthropic (Claude), Supabase (database), and Vercel (hosting).
        Your use of those services is governed by their own terms and policies. I&apos;m not responsible for
        their availability, pricing, or decisions.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Drafted replies are generated by AI. You&apos;re responsible for reviewing every draft before sending
        it. The AI will occasionally get things wrong, misunderstand context, or make claims on your behalf
        that you shouldn&apos;t make. Nothing is sent without you clicking &quot;Send reply&quot;.
      </p>

      <h2>No warranty</h2>
      <p>
        The Service is provided &quot;as is&quot;, without warranty of any kind, express or implied.
        I don&apos;t guarantee that it&apos;ll be available, accurate, bug-free, or fit for any particular
        purpose. Use it at your own risk.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, I&apos;m not liable for any indirect, incidental, special,
        or consequential damages arising from your use of the Service, including lost profits, lost
        business, lost data, or reputational harm. My total liability for any claim is capped at the
        amount you&apos;ve paid for the Service, which is zero.
      </p>

      <h2>Termination</h2>
      <p>
        You can stop using the Service at any time by deleting your account. I may suspend or terminate
        accounts that violate these terms or are used abusively.
      </p>

      <h2>Changes</h2>
      <p>
        I may update these terms occasionally. Material changes will be communicated on the site. Continued
        use of the Service after changes means you accept the updated terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions? Email <a href="mailto:stoddnetworks@gmail.com">stoddnetworks@gmail.com</a>.
      </p>
    </LegalLayout>
  );
}
